### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [plasma-umass/DoubleTake#27]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [xheap::initialize](https://github.com/plasma-umass/DoubleTake/blob/7ae8da91ba61454ca6915dd18080920ffa1af0de/include/xheap.hh#L27)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action.") ⇒ [watchpoint::installWatchpoints](https://github.com/plasma-umass/DoubleTake/blob/0df72109c7e443f54e8d7be52e94d7c19beeb914/source/watchpoint.cpp#L105)

**Comment by bpowers** [comment]
Hi @elfring,

The first one is not an issue - the only way pthread_mutex_init can fail is if you ask for unwindable mutexes.

We probably should check the result of sigaction.

How did you find these issues?

yours,
Bobby

**Comment by elfring** [comment]
The web search interface by GitHub can also be a tool for static source code analysis to some degree.

I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B) also for [this software](https://github.com/plasma-umass/DoubleTake/blob/0e8d698d23432f238865bc4e0f8fdca96415fdb8/heaplayers/locks/posixlock.h#L57)?

**Comment by bpowers** [comment]
@elfring Can you either share the analysis you are looking at, or explain in more detail what your question is?

**Comment by elfring** [comment]
Under which circumstances are you going to care for the remaining unchecked function return values?

**Comment by bpowers** [comment]
@elfring ideally, when I can see the results of a tool showing me that I should care.  So for the case of `pthread_mutex_*`, can your tool (using static analysis) show me that it is even _possible_ for those return values to be non-zero?

Additionally - can your tool ignore `pthread_mutex_*` functions, and tell me about other missing return values?  It isn't that I don't care in general - just that I am skeptical about some of the cases you have brought up (although I did add an `assert` for the `sigaction` you mentioned above).

**Comment by elfring** [comment]
It is easy sometimes to find more update candidates while it can be harder to agree on the complete software solution.
On which way would you like to continue?

**Comment by bpowers** [comment]
@elfring:

1 - Please tell us more about the tool you are running.
2 - Please post the full report of your tools output somewhere, for an example, see Coveralls: https://coveralls.io/builds/4446686/source?filename=mdl.c
3 - Allow us to hide false-positives.
4 - Allow us to re-run the tool when we push new commits to GitHub.

That would be 1000x more useful than you running a tool, once, in private, and opening up a trickle of issues related to code you don't understand deeply.  That would turn me into an advocate for your tool!

**Comment by elfring** [comment]
Some tools should be usable to check calls of functions with a non-void return type. Please choose one for your needs.

**Comment by bpowers** [comment]
@elfring can you please tell us more about the tool you ran on DoubleTake?

**Comment by elfring** [comment]
I suggest to reuse the following tools for finding more update candidates depending on your preferences for factors like [freedom](https://www.fsf.org/about/what-is-free-software), [licence costs](http://www.computerweekly.com/feature/Lower-your-software-licence-fees) and programming language support.
1. [AspectC++](http://aspectc.org/)
2. [Secure Programming Lint](http://splint.org/faq.html#quest9)
3. [Coccinelle](http://coccinelle.lip6.fr/)
4. [Coverity Scan](https://scan.coverity.com/)
5. [GitHub](https://help.github.com/articles/searching-code/)

**Comment by bpowers** [comment]
Hi @elfring - are your responses to my questions completely automated?

**Comment by elfring** [comment]
No. - I admit that I dare to repeat variations of previous answers for recurring issues.
